# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Function', [dirname(__file__)])
        except ImportError:
            import _Function
            return _Function
        if fp is not None:
            try:
                _mod = imp.load_module('_Function', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Function = swig_import_helper()
    del swig_import_helper
else:
    import _Function
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Function.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _Function.SwigPyIterator_value(self)
    def incr(self, n=1): return _Function.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _Function.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _Function.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _Function.SwigPyIterator_equal(self, *args)
    def copy(self): return _Function.SwigPyIterator_copy(self)
    def next(self): return _Function.SwigPyIterator_next(self)
    def __next__(self): return _Function.SwigPyIterator___next__(self)
    def previous(self): return _Function.SwigPyIterator_previous(self)
    def advance(self, *args): return _Function.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _Function.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _Function.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _Function.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _Function.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _Function.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _Function.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _Function.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Mesh(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Mesh, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Mesh, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def saveToHDF5(self, *args): return _Function.Mesh_saveToHDF5(self, *args)
    def cellPolyOrder(self, *args): return _Function.Mesh_cellPolyOrder(self, *args)
    def getActiveCellIDs(self): return _Function.Mesh_getActiveCellIDs(self)
    def hRefine(self, *args): return _Function.Mesh_hRefine(self, *args)
    def numActiveElements(self): return _Function.Mesh_numActiveElements(self)
    def numFluxDofs(self): return _Function.Mesh_numFluxDofs(self)
    def numFieldDofs(self): return _Function.Mesh_numFieldDofs(self)
    def numGlobalDofs(self): return _Function.Mesh_numGlobalDofs(self)
    def numElements(self): return _Function.Mesh_numElements(self)
    def pRefine(self, *args): return _Function.Mesh_pRefine(self, *args)
    def registerSolution(self, *args): return _Function.Mesh_registerSolution(self, *args)
    def vertexIndicesForCell(self, *args): return _Function.Mesh_vertexIndicesForCell(self, *args)
    def verticesForCell(self, *args): return _Function.Mesh_verticesForCell(self, *args)
    __swig_destroy__ = _Function.delete_Mesh
    __del__ = lambda self : None;
Mesh_swigregister = _Function.Mesh_swigregister
Mesh_swigregister(Mesh)

class MeshPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MeshPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MeshPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _Function.MeshPtr___deref__(self)
    def __init__(self): 
        this = _Function.new_MeshPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Function.delete_MeshPtr
    __del__ = lambda self : None;
    def saveToHDF5(self, *args): return _Function.MeshPtr_saveToHDF5(self, *args)
    def cellPolyOrder(self, *args): return _Function.MeshPtr_cellPolyOrder(self, *args)
    def getActiveCellIDs(self): return _Function.MeshPtr_getActiveCellIDs(self)
    def hRefine(self, *args): return _Function.MeshPtr_hRefine(self, *args)
    def numActiveElements(self): return _Function.MeshPtr_numActiveElements(self)
    def numFluxDofs(self): return _Function.MeshPtr_numFluxDofs(self)
    def numFieldDofs(self): return _Function.MeshPtr_numFieldDofs(self)
    def numGlobalDofs(self): return _Function.MeshPtr_numGlobalDofs(self)
    def numElements(self): return _Function.MeshPtr_numElements(self)
    def pRefine(self, *args): return _Function.MeshPtr_pRefine(self, *args)
    def registerSolution(self, *args): return _Function.MeshPtr_registerSolution(self, *args)
    def vertexIndicesForCell(self, *args): return _Function.MeshPtr_vertexIndicesForCell(self, *args)
    def verticesForCell(self, *args): return _Function.MeshPtr_verticesForCell(self, *args)
MeshPtr_swigregister = _Function.MeshPtr_swigregister
MeshPtr_swigregister(MeshPtr)

class SetInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SetInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SetInt, name)
    __repr__ = _swig_repr
    def iterator(self): return _Function.SetInt_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _Function.SetInt___nonzero__(self)
    def __bool__(self): return _Function.SetInt___bool__(self)
    def __len__(self): return _Function.SetInt___len__(self)
    def append(self, *args): return _Function.SetInt_append(self, *args)
    def __contains__(self, *args): return _Function.SetInt___contains__(self, *args)
    def __getitem__(self, *args): return _Function.SetInt___getitem__(self, *args)
    def add(self, *args): return _Function.SetInt_add(self, *args)
    def discard(self, *args): return _Function.SetInt_discard(self, *args)
    def __init__(self, *args): 
        this = _Function.new_SetInt(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _Function.SetInt_empty(self)
    def size(self): return _Function.SetInt_size(self)
    def clear(self): return _Function.SetInt_clear(self)
    def swap(self, *args): return _Function.SetInt_swap(self, *args)
    def count(self, *args): return _Function.SetInt_count(self, *args)
    def begin(self): return _Function.SetInt_begin(self)
    def end(self): return _Function.SetInt_end(self)
    def rbegin(self): return _Function.SetInt_rbegin(self)
    def rend(self): return _Function.SetInt_rend(self)
    def erase(self, *args): return _Function.SetInt_erase(self, *args)
    def find(self, *args): return _Function.SetInt_find(self, *args)
    def lower_bound(self, *args): return _Function.SetInt_lower_bound(self, *args)
    def upper_bound(self, *args): return _Function.SetInt_upper_bound(self, *args)
    def equal_range(self, *args): return _Function.SetInt_equal_range(self, *args)
    def insert(self, *args): return _Function.SetInt_insert(self, *args)
    __swig_destroy__ = _Function.delete_SetInt
    __del__ = lambda self : None;
SetInt_swigregister = _Function.SetInt_swigregister
SetInt_swigregister(SetInt)

class MapIntToFunction(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MapIntToFunction, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MapIntToFunction, name)
    __repr__ = _swig_repr
    def iterator(self): return _Function.MapIntToFunction_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _Function.MapIntToFunction___nonzero__(self)
    def __bool__(self): return _Function.MapIntToFunction___bool__(self)
    def __len__(self): return _Function.MapIntToFunction___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _Function.MapIntToFunction___getitem__(self, *args)
    def __delitem__(self, *args): return _Function.MapIntToFunction___delitem__(self, *args)
    def has_key(self, *args): return _Function.MapIntToFunction_has_key(self, *args)
    def keys(self): return _Function.MapIntToFunction_keys(self)
    def values(self): return _Function.MapIntToFunction_values(self)
    def items(self): return _Function.MapIntToFunction_items(self)
    def __contains__(self, *args): return _Function.MapIntToFunction___contains__(self, *args)
    def key_iterator(self): return _Function.MapIntToFunction_key_iterator(self)
    def value_iterator(self): return _Function.MapIntToFunction_value_iterator(self)
    def __setitem__(self, *args): return _Function.MapIntToFunction___setitem__(self, *args)
    def asdict(self): return _Function.MapIntToFunction_asdict(self)
    def __init__(self, *args): 
        this = _Function.new_MapIntToFunction(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _Function.MapIntToFunction_empty(self)
    def size(self): return _Function.MapIntToFunction_size(self)
    def clear(self): return _Function.MapIntToFunction_clear(self)
    def swap(self, *args): return _Function.MapIntToFunction_swap(self, *args)
    def get_allocator(self): return _Function.MapIntToFunction_get_allocator(self)
    def begin(self): return _Function.MapIntToFunction_begin(self)
    def end(self): return _Function.MapIntToFunction_end(self)
    def rbegin(self): return _Function.MapIntToFunction_rbegin(self)
    def rend(self): return _Function.MapIntToFunction_rend(self)
    def count(self, *args): return _Function.MapIntToFunction_count(self, *args)
    def erase(self, *args): return _Function.MapIntToFunction_erase(self, *args)
    def find(self, *args): return _Function.MapIntToFunction_find(self, *args)
    def lower_bound(self, *args): return _Function.MapIntToFunction_lower_bound(self, *args)
    def upper_bound(self, *args): return _Function.MapIntToFunction_upper_bound(self, *args)
    __swig_destroy__ = _Function.delete_MapIntToFunction
    __del__ = lambda self : None;
MapIntToFunction_swigregister = _Function.MapIntToFunction_swigregister
MapIntToFunction_swigregister(MapIntToFunction)

class Solution(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Solution, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Solution, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _Function.new_Solution(*args)
        try: self.this.append(this)
        except: self.this = this
    def solve(self): return _Function.Solution_solve(self)
    def addSolution(self, *args): return _Function.Solution_addSolution(self, *args)
    def clear(self): return _Function.Solution_clear(self)
    def cubatureEnrichmentDegree(self): return _Function.Solution_cubatureEnrichmentDegree(self)
    def setCubatureEnrichmentDegree(self, *args): return _Function.Solution_setCubatureEnrichmentDegree(self, *args)
    def L2NormOfSolution(self, *args): return _Function.Solution_L2NormOfSolution(self, *args)
    def projectOntoMesh(self, *args): return _Function.Solution_projectOntoMesh(self, *args)
    def energyErrorTotal(self): return _Function.Solution_energyErrorTotal(self)
    def setWriteMatrixToFile(self, *args): return _Function.Solution_setWriteMatrixToFile(self, *args)
    def setWriteMatrixToMatrixMarketFile(self, *args): return _Function.Solution_setWriteMatrixToMatrixMarketFile(self, *args)
    def setWriteRHSToMatrixMarketFile(self, *args): return _Function.Solution_setWriteRHSToMatrixMarketFile(self, *args)
    def mesh(self): return _Function.Solution_mesh(self)
    def bc(self): return _Function.Solution_bc(self)
    def rhs(self): return _Function.Solution_rhs(self)
    def ip(self): return _Function.Solution_ip(self)
    def setBC(self, *args): return _Function.Solution_setBC(self, *args)
    def setRHS(self, *args): return _Function.Solution_setRHS(self, *args)
    def setIP(self, *args): return _Function.Solution_setIP(self, *args)
    def save(self, *args): return _Function.Solution_save(self, *args)
    __swig_getmethods__["load"] = lambda x: _Function.Solution_load
    if _newclass:load = staticmethod(_Function.Solution_load)
    def saveToHDF5(self, *args): return _Function.Solution_saveToHDF5(self, *args)
    def loadFromHDF5(self, *args): return _Function.Solution_loadFromHDF5(self, *args)
    def setUseCondensedSolve(self, *args): return _Function.Solution_setUseCondensedSolve(self, *args)
    __swig_getmethods__["solution"] = lambda x: _Function.Solution_solution
    if _newclass:solution = staticmethod(_Function.Solution_solution)
    __swig_destroy__ = _Function.delete_Solution
    __del__ = lambda self : None;
Solution_swigregister = _Function.Solution_swigregister
Solution_swigregister(Solution)

def Solution_load(*args):
  return _Function.Solution_load(*args)
Solution_load = _Function.Solution_load

def Solution_solution(*args):
  return _Function.Solution_solution(*args)
Solution_solution = _Function.Solution_solution

class SolutionPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SolutionPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SolutionPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _Function.SolutionPtr___deref__(self)
    def __init__(self): 
        this = _Function.new_SolutionPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Function.delete_SolutionPtr
    __del__ = lambda self : None;
    def solve(self): return _Function.SolutionPtr_solve(self)
    def addSolution(self, *args): return _Function.SolutionPtr_addSolution(self, *args)
    def clear(self): return _Function.SolutionPtr_clear(self)
    def cubatureEnrichmentDegree(self): return _Function.SolutionPtr_cubatureEnrichmentDegree(self)
    def setCubatureEnrichmentDegree(self, *args): return _Function.SolutionPtr_setCubatureEnrichmentDegree(self, *args)
    def L2NormOfSolution(self, *args): return _Function.SolutionPtr_L2NormOfSolution(self, *args)
    def projectOntoMesh(self, *args): return _Function.SolutionPtr_projectOntoMesh(self, *args)
    def energyErrorTotal(self): return _Function.SolutionPtr_energyErrorTotal(self)
    def setWriteMatrixToFile(self, *args): return _Function.SolutionPtr_setWriteMatrixToFile(self, *args)
    def setWriteMatrixToMatrixMarketFile(self, *args): return _Function.SolutionPtr_setWriteMatrixToMatrixMarketFile(self, *args)
    def setWriteRHSToMatrixMarketFile(self, *args): return _Function.SolutionPtr_setWriteRHSToMatrixMarketFile(self, *args)
    def mesh(self): return _Function.SolutionPtr_mesh(self)
    def bc(self): return _Function.SolutionPtr_bc(self)
    def rhs(self): return _Function.SolutionPtr_rhs(self)
    def ip(self): return _Function.SolutionPtr_ip(self)
    def setBC(self, *args): return _Function.SolutionPtr_setBC(self, *args)
    def setRHS(self, *args): return _Function.SolutionPtr_setRHS(self, *args)
    def setIP(self, *args): return _Function.SolutionPtr_setIP(self, *args)
    def save(self, *args): return _Function.SolutionPtr_save(self, *args)
    def load(self, *args): return _Function.SolutionPtr_load(self, *args)
    def saveToHDF5(self, *args): return _Function.SolutionPtr_saveToHDF5(self, *args)
    def loadFromHDF5(self, *args): return _Function.SolutionPtr_loadFromHDF5(self, *args)
    def setUseCondensedSolve(self, *args): return _Function.SolutionPtr_setUseCondensedSolve(self, *args)
    def solution(self, *args): return _Function.SolutionPtr_solution(self, *args)
SolutionPtr_swigregister = _Function.SolutionPtr_swigregister
SolutionPtr_swigregister(SolutionPtr)

class Function(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Function, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Function, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def displayString(self): return _Function.Function_displayString(self)
    def x(self): return _Function.Function_x(self)
    def y(self): return _Function.Function_y(self)
    def div(self): return _Function.Function_div(self)
    def rank(self): return _Function.Function_rank(self)
    def l2norm(self, *args): return _Function.Function_l2norm(self, *args)
    def dx(self): return _Function.Function_dx(self)
    def dy(self): return _Function.Function_dy(self)
    def grad(self): return _Function.Function_grad(self)
    __swig_getmethods__["evaluate"] = lambda x: _Function.Function_evaluate
    if _newclass:evaluate = staticmethod(_Function.Function_evaluate)
    __swig_getmethods__["xn"] = lambda x: _Function.Function_xn
    if _newclass:xn = staticmethod(_Function.Function_xn)
    __swig_getmethods__["yn"] = lambda x: _Function.Function_yn
    if _newclass:yn = staticmethod(_Function.Function_yn)
    __swig_getmethods__["composedFunction"] = lambda x: _Function.Function_composedFunction
    if _newclass:composedFunction = staticmethod(_Function.Function_composedFunction)
    __swig_getmethods__["constant"] = lambda x: _Function.Function_constant
    if _newclass:constant = staticmethod(_Function.Function_constant)
    __swig_getmethods__["vectorize"] = lambda x: _Function.Function_vectorize
    if _newclass:vectorize = staticmethod(_Function.Function_vectorize)
    __swig_getmethods__["normal"] = lambda x: _Function.Function_normal
    if _newclass:normal = staticmethod(_Function.Function_normal)
    __swig_getmethods__["solution"] = lambda x: _Function.Function_solution
    if _newclass:solution = staticmethod(_Function.Function_solution)
    def __str__(self): return _Function.Function___str__(self)
    __swig_destroy__ = _Function.delete_Function
    __del__ = lambda self : None;
Function_swigregister = _Function.Function_swigregister
Function_swigregister(Function)

def Function_evaluate(*args):
  return _Function.Function_evaluate(*args)
Function_evaluate = _Function.Function_evaluate

def Function_xn(n=1):
  return _Function.Function_xn(n)
Function_xn = _Function.Function_xn

def Function_yn(n=1):
  return _Function.Function_yn(n)
Function_yn = _Function.Function_yn

def Function_composedFunction(*args):
  return _Function.Function_composedFunction(*args)
Function_composedFunction = _Function.Function_composedFunction

def Function_constant(*args):
  return _Function.Function_constant(*args)
Function_constant = _Function.Function_constant

def Function_vectorize(*args):
  return _Function.Function_vectorize(*args)
Function_vectorize = _Function.Function_vectorize

def Function_normal():
  return _Function.Function_normal()
Function_normal = _Function.Function_normal

def Function_solution(*args):
  return _Function.Function_solution(*args)
Function_solution = _Function.Function_solution

class FunctionPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FunctionPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FunctionPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _Function.FunctionPtr___deref__(self)
    def __add__(self, *args): return _Function.FunctionPtr___add__(self, *args)
    def __radd__(self, *args): return _Function.FunctionPtr___radd__(self, *args)
    def __sub__(self, *args): return _Function.FunctionPtr___sub__(self, *args)
    def __rsub__(self, *args): return _Function.FunctionPtr___rsub__(self, *args)
    def __div__(self, *args): return _Function.FunctionPtr___div__(self, *args)
    def __rdiv__(self, *args): return _Function.FunctionPtr___rdiv__(self, *args)
    def __mul__(self, *args): return _Function.FunctionPtr___mul__(self, *args)
    def __rmul__(self, *args): return _Function.FunctionPtr___rmul__(self, *args)
    def __neg__(self): return _Function.FunctionPtr___neg__(self)
    def __init__(self): 
        this = _Function.new_FunctionPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Function.delete_FunctionPtr
    __del__ = lambda self : None;
    def displayString(self): return _Function.FunctionPtr_displayString(self)
    def evaluate(self, *args): return _Function.FunctionPtr_evaluate(self, *args)
    def x(self): return _Function.FunctionPtr_x(self)
    def y(self): return _Function.FunctionPtr_y(self)
    def div(self): return _Function.FunctionPtr_div(self)
    def rank(self): return _Function.FunctionPtr_rank(self)
    def l2norm(self, *args): return _Function.FunctionPtr_l2norm(self, *args)
    def dx(self): return _Function.FunctionPtr_dx(self)
    def dy(self): return _Function.FunctionPtr_dy(self)
    def grad(self): return _Function.FunctionPtr_grad(self)
    def xn(self, n=1): return _Function.FunctionPtr_xn(self, n)
    def yn(self, n=1): return _Function.FunctionPtr_yn(self, n)
    def composedFunction(self, *args): return _Function.FunctionPtr_composedFunction(self, *args)
    def constant(self, *args): return _Function.FunctionPtr_constant(self, *args)
    def vectorize(self, *args): return _Function.FunctionPtr_vectorize(self, *args)
    def normal(self): return _Function.FunctionPtr_normal(self)
    def solution(self, *args): return _Function.FunctionPtr_solution(self, *args)
    def __str__(self): return _Function.FunctionPtr___str__(self)
FunctionPtr_swigregister = _Function.FunctionPtr_swigregister
FunctionPtr_swigregister(FunctionPtr)

# This file is compatible with both classic and new-style classes.


