# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LinearTerm', [dirname(__file__)])
        except ImportError:
            import _LinearTerm
            return _LinearTerm
        if fp is not None:
            try:
                _mod = imp.load_module('_LinearTerm', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _LinearTerm = swig_import_helper()
    del swig_import_helper
else:
    import _LinearTerm
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


HGRAD = _LinearTerm.HGRAD
HCURL = _LinearTerm.HCURL
HDIV = _LinearTerm.HDIV
HGRAD_DISC = _LinearTerm.HGRAD_DISC
HCURL_DISC = _LinearTerm.HCURL_DISC
HDIV_DISC = _LinearTerm.HDIV_DISC
HDIV_FREE = _LinearTerm.HDIV_FREE
L2 = _LinearTerm.L2
CONSTANT_SCALAR = _LinearTerm.CONSTANT_SCALAR
VECTOR_HGRAD = _LinearTerm.VECTOR_HGRAD
VECTOR_HGRAD_DISC = _LinearTerm.VECTOR_HGRAD_DISC
VECTOR_L2 = _LinearTerm.VECTOR_L2
UNKNOWN_FS = _LinearTerm.UNKNOWN_FS
OP_VALUE = _LinearTerm.OP_VALUE
OP_GRAD = _LinearTerm.OP_GRAD
OP_CURL = _LinearTerm.OP_CURL
OP_DIV = _LinearTerm.OP_DIV
OP_D1 = _LinearTerm.OP_D1
OP_D2 = _LinearTerm.OP_D2
OP_D3 = _LinearTerm.OP_D3
OP_D4 = _LinearTerm.OP_D4
OP_D5 = _LinearTerm.OP_D5
OP_D6 = _LinearTerm.OP_D6
OP_D7 = _LinearTerm.OP_D7
OP_D8 = _LinearTerm.OP_D8
OP_D9 = _LinearTerm.OP_D9
OP_D10 = _LinearTerm.OP_D10
OP_X = _LinearTerm.OP_X
OP_Y = _LinearTerm.OP_Y
OP_Z = _LinearTerm.OP_Z
OP_DX = _LinearTerm.OP_DX
OP_DY = _LinearTerm.OP_DY
OP_DZ = _LinearTerm.OP_DZ
OP_CROSS_NORMAL = _LinearTerm.OP_CROSS_NORMAL
OP_DOT_NORMAL = _LinearTerm.OP_DOT_NORMAL
OP_TIMES_NORMAL = _LinearTerm.OP_TIMES_NORMAL
OP_TIMES_NORMAL_X = _LinearTerm.OP_TIMES_NORMAL_X
OP_TIMES_NORMAL_Y = _LinearTerm.OP_TIMES_NORMAL_Y
OP_TIMES_NORMAL_Z = _LinearTerm.OP_TIMES_NORMAL_Z
OP_TIMES_NORMAL_T = _LinearTerm.OP_TIMES_NORMAL_T
OP_VECTORIZE_VALUE = _LinearTerm.OP_VECTORIZE_VALUE
TEST = _LinearTerm.TEST
FIELD = _LinearTerm.FIELD
TRACE = _LinearTerm.TRACE
FLUX = _LinearTerm.FLUX
UNKNOWN_TYPE = _LinearTerm.UNKNOWN_TYPE
MIXED_TYPE = _LinearTerm.MIXED_TYPE
class Var(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Var, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Var, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def ID(self): return _LinearTerm.Var_ID(self)
    def name(self): return _LinearTerm.Var_name(self)
    def displayString(self): return _LinearTerm.Var_displayString(self)
    def rank(self): return _LinearTerm.Var_rank(self)
    def space(self): return _LinearTerm.Var_space(self)
    def varType(self): return _LinearTerm.Var_varType(self)
    def op(self): return _LinearTerm.Var_op(self)
    def termTraced(self): return _LinearTerm.Var_termTraced(self)
    def grad(self): return _LinearTerm.Var_grad(self)
    def div(self): return _LinearTerm.Var_div(self)
    def curl(self, *args): return _LinearTerm.Var_curl(self, *args)
    def dx(self): return _LinearTerm.Var_dx(self)
    def dy(self): return _LinearTerm.Var_dy(self)
    def x(self): return _LinearTerm.Var_x(self)
    def y(self): return _LinearTerm.Var_y(self)
    __swig_destroy__ = _LinearTerm.delete_Var
    __del__ = lambda self : None;
Var_swigregister = _LinearTerm.Var_swigregister
Var_swigregister(Var)

class VarPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VarPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VarPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _LinearTerm.VarPtr___deref__(self)
    def __mul__(self, *args): return _LinearTerm.VarPtr___mul__(self, *args)
    def __rmul__(self, *args): return _LinearTerm.VarPtr___rmul__(self, *args)
    def __add__(self, *args): return _LinearTerm.VarPtr___add__(self, *args)
    def __div__(self, *args): return _LinearTerm.VarPtr___div__(self, *args)
    def __sub__(self, *args): return _LinearTerm.VarPtr___sub__(self, *args)
    def __init__(self): 
        this = _LinearTerm.new_VarPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LinearTerm.delete_VarPtr
    __del__ = lambda self : None;
    def ID(self): return _LinearTerm.VarPtr_ID(self)
    def name(self): return _LinearTerm.VarPtr_name(self)
    def displayString(self): return _LinearTerm.VarPtr_displayString(self)
    def rank(self): return _LinearTerm.VarPtr_rank(self)
    def space(self): return _LinearTerm.VarPtr_space(self)
    def varType(self): return _LinearTerm.VarPtr_varType(self)
    def op(self): return _LinearTerm.VarPtr_op(self)
    def termTraced(self): return _LinearTerm.VarPtr_termTraced(self)
    def grad(self): return _LinearTerm.VarPtr_grad(self)
    def div(self): return _LinearTerm.VarPtr_div(self)
    def curl(self, *args): return _LinearTerm.VarPtr_curl(self, *args)
    def dx(self): return _LinearTerm.VarPtr_dx(self)
    def dy(self): return _LinearTerm.VarPtr_dy(self)
    def x(self): return _LinearTerm.VarPtr_x(self)
    def y(self): return _LinearTerm.VarPtr_y(self)
VarPtr_swigregister = _LinearTerm.VarPtr_swigregister
VarPtr_swigregister(VarPtr)

class LinearTerm(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinearTerm, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinearTerm, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def varIDs(self): return _LinearTerm.LinearTerm_varIDs(self)
    def termType(self): return _LinearTerm.LinearTerm_termType(self)
    def evaluate(self, *args): return _LinearTerm.LinearTerm_evaluate(self, *args)
    def rank(self): return _LinearTerm.LinearTerm_rank(self)
    def displayString(self): return _LinearTerm.LinearTerm_displayString(self)
    __swig_destroy__ = _LinearTerm.delete_LinearTerm
    __del__ = lambda self : None;
LinearTerm_swigregister = _LinearTerm.LinearTerm_swigregister
LinearTerm_swigregister(LinearTerm)

class LinearTermPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinearTermPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinearTermPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _LinearTerm.LinearTermPtr___deref__(self)
    def __radd__(self, *args): return _LinearTerm.LinearTermPtr___radd__(self, *args)
    def __mul__(self, *args): return _LinearTerm.LinearTermPtr___mul__(self, *args)
    def __add__(self, *args): return _LinearTerm.LinearTermPtr___add__(self, *args)
    def __div__(self, *args): return _LinearTerm.LinearTermPtr___div__(self, *args)
    def __neg__(self, *args): return _LinearTerm.LinearTermPtr___neg__(self, *args)
    def __rsub__(self, *args): return _LinearTerm.LinearTermPtr___rsub__(self, *args)
    def __sub__(self, *args): return _LinearTerm.LinearTermPtr___sub__(self, *args)
    def __init__(self): 
        this = _LinearTerm.new_LinearTermPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LinearTerm.delete_LinearTermPtr
    __del__ = lambda self : None;
    def varIDs(self): return _LinearTerm.LinearTermPtr_varIDs(self)
    def termType(self): return _LinearTerm.LinearTermPtr_termType(self)
    def evaluate(self, *args): return _LinearTerm.LinearTermPtr_evaluate(self, *args)
    def rank(self): return _LinearTerm.LinearTermPtr_rank(self)
    def displayString(self): return _LinearTerm.LinearTermPtr_displayString(self)
LinearTermPtr_swigregister = _LinearTerm.LinearTermPtr_swigregister
LinearTermPtr_swigregister(LinearTermPtr)

# This file is compatible with both classic and new-style classes.


