# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LinearTerm', [dirname(__file__)])
        except ImportError:
            import _LinearTerm
            return _LinearTerm
        if fp is not None:
            try:
                _mod = imp.load_module('_LinearTerm', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _LinearTerm = swig_import_helper()
    del swig_import_helper
else:
    import _LinearTerm
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


HGRAD = _LinearTerm.HGRAD
HCURL = _LinearTerm.HCURL
HDIV = _LinearTerm.HDIV
HGRAD_DISC = _LinearTerm.HGRAD_DISC
HCURL_DISC = _LinearTerm.HCURL_DISC
HDIV_DISC = _LinearTerm.HDIV_DISC
HDIV_FREE = _LinearTerm.HDIV_FREE
L2 = _LinearTerm.L2
CONSTANT_SCALAR = _LinearTerm.CONSTANT_SCALAR
VECTOR_HGRAD = _LinearTerm.VECTOR_HGRAD
VECTOR_HGRAD_DISC = _LinearTerm.VECTOR_HGRAD_DISC
VECTOR_L2 = _LinearTerm.VECTOR_L2
UNKNOWN_FS = _LinearTerm.UNKNOWN_FS
class Var(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Var, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Var, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _LinearTerm.delete_Var
    __del__ = lambda self : None;
Var_swigregister = _LinearTerm.Var_swigregister
Var_swigregister(Var)

class VarPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VarPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VarPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _LinearTerm.VarPtr___deref__(self)
    def __init__(self): 
        this = _LinearTerm.new_VarPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LinearTerm.delete_VarPtr
    __del__ = lambda self : None;
VarPtr_swigregister = _LinearTerm.VarPtr_swigregister
VarPtr_swigregister(VarPtr)

class LinearTerm(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinearTerm, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinearTerm, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def varIDs(self): return _LinearTerm.LinearTerm_varIDs(self)
    def termType(self): return _LinearTerm.LinearTerm_termType(self)
    def evaluate(self, *args): return _LinearTerm.LinearTerm_evaluate(self, *args)
    def rank(self): return _LinearTerm.LinearTerm_rank(self)
    def displayString(self): return _LinearTerm.LinearTerm_displayString(self)
    __swig_destroy__ = _LinearTerm.delete_LinearTerm
    __del__ = lambda self : None;
LinearTerm_swigregister = _LinearTerm.LinearTerm_swigregister
LinearTerm_swigregister(LinearTerm)

class LinearTermPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinearTermPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinearTermPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _LinearTerm.LinearTermPtr___deref__(self)
    def __radd__(self, *args): return _LinearTerm.LinearTermPtr___radd__(self, *args)
    def __mul__(self, *args): return _LinearTerm.LinearTermPtr___mul__(self, *args)
    def __add__(self, *args): return _LinearTerm.LinearTermPtr___add__(self, *args)
    def __div__(self, *args): return _LinearTerm.LinearTermPtr___div__(self, *args)
    def __neg__(self, *args): return _LinearTerm.LinearTermPtr___neg__(self, *args)
    def __rsub__(self, *args): return _LinearTerm.LinearTermPtr___rsub__(self, *args)
    def __sub__(self, *args): return _LinearTerm.LinearTermPtr___sub__(self, *args)
    def __init__(self): 
        this = _LinearTerm.new_LinearTermPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LinearTerm.delete_LinearTermPtr
    __del__ = lambda self : None;
    def varIDs(self): return _LinearTerm.LinearTermPtr_varIDs(self)
    def termType(self): return _LinearTerm.LinearTermPtr_termType(self)
    def evaluate(self, *args): return _LinearTerm.LinearTermPtr_evaluate(self, *args)
    def rank(self): return _LinearTerm.LinearTermPtr_rank(self)
    def displayString(self): return _LinearTerm.LinearTermPtr_displayString(self)
LinearTermPtr_swigregister = _LinearTerm.LinearTermPtr_swigregister
LinearTermPtr_swigregister(LinearTermPtr)

# This file is compatible with both classic and new-style classes.


