# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_MeshFactory', [dirname(__file__)])
        except ImportError:
            import _MeshFactory
            return _MeshFactory
        if fp is not None:
            try:
                _mod = imp.load_module('_MeshFactory', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _MeshFactory = swig_import_helper()
    del swig_import_helper
else:
    import _MeshFactory
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MeshFactory.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _MeshFactory.SwigPyIterator_value(self)
    def incr(self, n=1): return _MeshFactory.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _MeshFactory.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _MeshFactory.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _MeshFactory.SwigPyIterator_equal(self, *args)
    def copy(self): return _MeshFactory.SwigPyIterator_copy(self)
    def next(self): return _MeshFactory.SwigPyIterator_next(self)
    def __next__(self): return _MeshFactory.SwigPyIterator___next__(self)
    def previous(self): return _MeshFactory.SwigPyIterator_previous(self)
    def advance(self, *args): return _MeshFactory.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _MeshFactory.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _MeshFactory.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _MeshFactory.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _MeshFactory.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _MeshFactory.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _MeshFactory.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _MeshFactory.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _MeshFactory.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _MeshFactory.IntVector___nonzero__(self)
    def __bool__(self): return _MeshFactory.IntVector___bool__(self)
    def __len__(self): return _MeshFactory.IntVector___len__(self)
    def pop(self): return _MeshFactory.IntVector_pop(self)
    def __getslice__(self, *args): return _MeshFactory.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _MeshFactory.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _MeshFactory.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _MeshFactory.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _MeshFactory.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _MeshFactory.IntVector___setitem__(self, *args)
    def append(self, *args): return _MeshFactory.IntVector_append(self, *args)
    def empty(self): return _MeshFactory.IntVector_empty(self)
    def size(self): return _MeshFactory.IntVector_size(self)
    def clear(self): return _MeshFactory.IntVector_clear(self)
    def swap(self, *args): return _MeshFactory.IntVector_swap(self, *args)
    def get_allocator(self): return _MeshFactory.IntVector_get_allocator(self)
    def begin(self): return _MeshFactory.IntVector_begin(self)
    def end(self): return _MeshFactory.IntVector_end(self)
    def rbegin(self): return _MeshFactory.IntVector_rbegin(self)
    def rend(self): return _MeshFactory.IntVector_rend(self)
    def pop_back(self): return _MeshFactory.IntVector_pop_back(self)
    def erase(self, *args): return _MeshFactory.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _MeshFactory.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _MeshFactory.IntVector_push_back(self, *args)
    def front(self): return _MeshFactory.IntVector_front(self)
    def back(self): return _MeshFactory.IntVector_back(self)
    def assign(self, *args): return _MeshFactory.IntVector_assign(self, *args)
    def resize(self, *args): return _MeshFactory.IntVector_resize(self, *args)
    def insert(self, *args): return _MeshFactory.IntVector_insert(self, *args)
    def reserve(self, *args): return _MeshFactory.IntVector_reserve(self, *args)
    def capacity(self): return _MeshFactory.IntVector_capacity(self)
    __swig_destroy__ = _MeshFactory.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _MeshFactory.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _MeshFactory.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _MeshFactory.DoubleVector___nonzero__(self)
    def __bool__(self): return _MeshFactory.DoubleVector___bool__(self)
    def __len__(self): return _MeshFactory.DoubleVector___len__(self)
    def pop(self): return _MeshFactory.DoubleVector_pop(self)
    def __getslice__(self, *args): return _MeshFactory.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _MeshFactory.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _MeshFactory.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _MeshFactory.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _MeshFactory.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _MeshFactory.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _MeshFactory.DoubleVector_append(self, *args)
    def empty(self): return _MeshFactory.DoubleVector_empty(self)
    def size(self): return _MeshFactory.DoubleVector_size(self)
    def clear(self): return _MeshFactory.DoubleVector_clear(self)
    def swap(self, *args): return _MeshFactory.DoubleVector_swap(self, *args)
    def get_allocator(self): return _MeshFactory.DoubleVector_get_allocator(self)
    def begin(self): return _MeshFactory.DoubleVector_begin(self)
    def end(self): return _MeshFactory.DoubleVector_end(self)
    def rbegin(self): return _MeshFactory.DoubleVector_rbegin(self)
    def rend(self): return _MeshFactory.DoubleVector_rend(self)
    def pop_back(self): return _MeshFactory.DoubleVector_pop_back(self)
    def erase(self, *args): return _MeshFactory.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _MeshFactory.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _MeshFactory.DoubleVector_push_back(self, *args)
    def front(self): return _MeshFactory.DoubleVector_front(self)
    def back(self): return _MeshFactory.DoubleVector_back(self)
    def assign(self, *args): return _MeshFactory.DoubleVector_assign(self, *args)
    def resize(self, *args): return _MeshFactory.DoubleVector_resize(self, *args)
    def insert(self, *args): return _MeshFactory.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _MeshFactory.DoubleVector_reserve(self, *args)
    def capacity(self): return _MeshFactory.DoubleVector_capacity(self)
    __swig_destroy__ = _MeshFactory.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _MeshFactory.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class MeshFactory(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MeshFactory, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MeshFactory, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["loadFromHDF5"] = lambda x: _MeshFactory.MeshFactory_loadFromHDF5
    if _newclass:loadFromHDF5 = staticmethod(_MeshFactory.MeshFactory_loadFromHDF5)
    __swig_getmethods__["rectilinearMesh"] = lambda x: _MeshFactory.MeshFactory_rectilinearMesh
    if _newclass:rectilinearMesh = staticmethod(_MeshFactory.MeshFactory_rectilinearMesh)
    __swig_getmethods__["readTriangle"] = lambda x: _MeshFactory.MeshFactory_readTriangle
    if _newclass:readTriangle = staticmethod(_MeshFactory.MeshFactory_readTriangle)
    __swig_destroy__ = _MeshFactory.delete_MeshFactory
    __del__ = lambda self : None;
MeshFactory_swigregister = _MeshFactory.MeshFactory_swigregister
MeshFactory_swigregister(MeshFactory)

def MeshFactory_loadFromHDF5(*args):
  return _MeshFactory.MeshFactory_loadFromHDF5(*args)
MeshFactory_loadFromHDF5 = _MeshFactory.MeshFactory_loadFromHDF5

def MeshFactory_rectilinearMesh(*args):
  return _MeshFactory.MeshFactory_rectilinearMesh(*args)
MeshFactory_rectilinearMesh = _MeshFactory.MeshFactory_rectilinearMesh

def MeshFactory_readTriangle(*args):
  return _MeshFactory.MeshFactory_readTriangle(*args)
MeshFactory_readTriangle = _MeshFactory.MeshFactory_readTriangle

# This file is compatible with both classic and new-style classes.


