# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_SpatialFilter', [dirname(__file__)])
        except ImportError:
            import _SpatialFilter
            return _SpatialFilter
        if fp is not None:
            try:
                _mod = imp.load_module('_SpatialFilter', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _SpatialFilter = swig_import_helper()
    del swig_import_helper
else:
    import _SpatialFilter
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SpatialFilter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpatialFilter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpatialFilter, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def matchesPoint(self, *args): return _SpatialFilter.SpatialFilter_matchesPoint(self, *args)
    __swig_getmethods__["unionFilter"] = lambda x: _SpatialFilter.SpatialFilter_unionFilter
    if _newclass:unionFilter = staticmethod(_SpatialFilter.SpatialFilter_unionFilter)
    __swig_getmethods__["intersectionFilter"] = lambda x: _SpatialFilter.SpatialFilter_intersectionFilter
    if _newclass:intersectionFilter = staticmethod(_SpatialFilter.SpatialFilter_intersectionFilter)
    __swig_getmethods__["matchingX"] = lambda x: _SpatialFilter.SpatialFilter_matchingX
    if _newclass:matchingX = staticmethod(_SpatialFilter.SpatialFilter_matchingX)
    __swig_getmethods__["matchingY"] = lambda x: _SpatialFilter.SpatialFilter_matchingY
    if _newclass:matchingY = staticmethod(_SpatialFilter.SpatialFilter_matchingY)
    __swig_destroy__ = _SpatialFilter.delete_SpatialFilter
    __del__ = lambda self : None;
SpatialFilter_swigregister = _SpatialFilter.SpatialFilter_swigregister
SpatialFilter_swigregister(SpatialFilter)

def SpatialFilter_unionFilter(*args):
  return _SpatialFilter.SpatialFilter_unionFilter(*args)
SpatialFilter_unionFilter = _SpatialFilter.SpatialFilter_unionFilter

def SpatialFilter_intersectionFilter(*args):
  return _SpatialFilter.SpatialFilter_intersectionFilter(*args)
SpatialFilter_intersectionFilter = _SpatialFilter.SpatialFilter_intersectionFilter

def SpatialFilter_matchingX(*args):
  return _SpatialFilter.SpatialFilter_matchingX(*args)
SpatialFilter_matchingX = _SpatialFilter.SpatialFilter_matchingX

def SpatialFilter_matchingY(*args):
  return _SpatialFilter.SpatialFilter_matchingY(*args)
SpatialFilter_matchingY = _SpatialFilter.SpatialFilter_matchingY

class SpatialFilterPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpatialFilterPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpatialFilterPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _SpatialFilter.SpatialFilterPtr___deref__(self)
    def __or__(self, *args): return _SpatialFilter.SpatialFilterPtr___or__(self, *args)
    def __and__(self, *args): return _SpatialFilter.SpatialFilterPtr___and__(self, *args)
    def __init__(self): 
        this = _SpatialFilter.new_SpatialFilterPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _SpatialFilter.delete_SpatialFilterPtr
    __del__ = lambda self : None;
    def matchesPoint(self, *args): return _SpatialFilter.SpatialFilterPtr_matchesPoint(self, *args)
    def unionFilter(self, *args): return _SpatialFilter.SpatialFilterPtr_unionFilter(self, *args)
    def intersectionFilter(self, *args): return _SpatialFilter.SpatialFilterPtr_intersectionFilter(self, *args)
    def matchingX(self, *args): return _SpatialFilter.SpatialFilterPtr_matchingX(self, *args)
    def matchingY(self, *args): return _SpatialFilter.SpatialFilterPtr_matchingY(self, *args)
SpatialFilterPtr_swigregister = _SpatialFilter.SpatialFilterPtr_swigregister
SpatialFilterPtr_swigregister(SpatialFilterPtr)

# This file is compatible with both classic and new-style classes.


