# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Var', [dirname(__file__)])
        except ImportError:
            import _Var
            return _Var
        if fp is not None:
            try:
                _mod = imp.load_module('_Var', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Var = swig_import_helper()
    del swig_import_helper
else:
    import _Var
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Solution(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Solution, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Solution, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _Var.new_Solution(*args)
        try: self.this.append(this)
        except: self.this = this
    def solve(self): return _Var.Solution_solve(self)
    def addSolution(self, *args): return _Var.Solution_addSolution(self, *args)
    def clear(self): return _Var.Solution_clear(self)
    def cubatureEnrichmentDegree(self): return _Var.Solution_cubatureEnrichmentDegree(self)
    def setCubatureEnrichmentDegree(self, *args): return _Var.Solution_setCubatureEnrichmentDegree(self, *args)
    def L2NormOfSolution(self, *args): return _Var.Solution_L2NormOfSolution(self, *args)
    def projectOntoMesh(self, *args): return _Var.Solution_projectOntoMesh(self, *args)
    def energyErrorTotal(self): return _Var.Solution_energyErrorTotal(self)
    def setWriteMatrixToFile(self, *args): return _Var.Solution_setWriteMatrixToFile(self, *args)
    def setWriteMatrixToMatrixMarketFile(self, *args): return _Var.Solution_setWriteMatrixToMatrixMarketFile(self, *args)
    def setWriteRHSToMatrixMarketFile(self, *args): return _Var.Solution_setWriteRHSToMatrixMarketFile(self, *args)
    def mesh(self): return _Var.Solution_mesh(self)
    def bc(self): return _Var.Solution_bc(self)
    def rhs(self): return _Var.Solution_rhs(self)
    def ip(self): return _Var.Solution_ip(self)
    def setBC(self, *args): return _Var.Solution_setBC(self, *args)
    def setRHS(self, *args): return _Var.Solution_setRHS(self, *args)
    def setIP(self, *args): return _Var.Solution_setIP(self, *args)
    def save(self, *args): return _Var.Solution_save(self, *args)
    __swig_getmethods__["load"] = lambda x: _Var.Solution_load
    if _newclass:load = staticmethod(_Var.Solution_load)
    def saveToHDF5(self, *args): return _Var.Solution_saveToHDF5(self, *args)
    def loadFromHDF5(self, *args): return _Var.Solution_loadFromHDF5(self, *args)
    def setUseCondensedSolve(self, *args): return _Var.Solution_setUseCondensedSolve(self, *args)
    __swig_destroy__ = _Var.delete_Solution
    __del__ = lambda self : None;
Solution_swigregister = _Var.Solution_swigregister
Solution_swigregister(Solution)

def Solution_load(*args):
  return _Var.Solution_load(*args)
Solution_load = _Var.Solution_load

# This file is compatible with both classic and new-style classes.


